AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Stream reader
Globals:
  Function:
    Runtime: "nodejs12.x"

Parameters:
  Stage:
    Type: String
    Default: dev
  StreamName: 
    Type: String
    Default: filtered

Resources:


  StreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -, [StreamProcessor, !Ref "Stage"]]
      Handler: stream.handler
      CodeUri: src/
      Role: !GetAtt [ StreamProcExecutionRole, Arn ]
      Environment:
        Variables:
          STAGE: !Ref Stage
          SUBTABLE: !Join [-, [Subscriptions, !Ref 'Stage']]
      Events:
        StreamEvent:
          Type: Kinesis
          Properties:
            Stream: !Sub 'arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${StreamName}'
            StartingPosition: LATEST
            BatchSize: 10

  StreamProcExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [-, [StreamProcRole, !Ref 'Stage']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:

        - PolicyName: CreateAndWriteLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
                
        - PolicyName: StreamAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListStreams
                Resource: 
                  !Sub 'arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${StreamName}'

 
                   
